name       : libharu
version    : 2.3.0
release    : 1
source     :
    - https://github.com/libharu/libharu/archive/RELEASE_2_3_0.tar.gz : 8f9e68cc5d5f7d53d1bc61a1ed876add1faf4f91070dbc360d8b259f46d9a4d2
license    : Zlib
component  : programming.library
homepage   : http://libharu.org/
summary    : Free PDF library
description: |
    Haru is a free, cross platform, open-sourced software library for generating PDF.
builddeps  :
    - pkgconfig(libpng)
libsplit   : no
setup      : |
    %apply_patches
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
